- name: "Start nginx"
  hosts: "nginx"
  become: "yes"
  tasks:
    - include_role:
        name: "manala.nginx"
    - template:
        src: "index.html.j2"
        dest: "/usr/share/nginx/html/index.html"
